services:
  app:
    image: node:20-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev --host 0.0.0.0"
    environment:
      - NODE_ENV=development
    env_file:
      - .env.development
    stdin_open: true
    tty: true